version: '3.8'

services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6000:6379"
    restart: always

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "4000:5432"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "postgres"
    restart: always

  test_saham_rakyat:
    container_name: test_saham_rakyat
    # image: test_saham_rakyat
    build: .
    ports:
      - "3000:7000"
    environment:
      REDIS_ADDRESS: "redis:6379"
      REDIS_DATABASE: "0"
      PG_HOST: "postgres" 
      PG_USER: "postgres" 
      PG_PASSWORD: "password" 
      PG_PORT: "5432"
      PG_DBNAME: "postgres"
      PORT: "7000"
    restart: always
